# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

dist: trusty

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_packages:
  - devtools

r_github_packages:
  - seananderson/glmmfields
  - pbs-software/pbs-data/PBSdata

