# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: devel
sudo: required
cache: packages

warnings_are_errors: false

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_github_packages:
  - pbs-software/pbs-data/PBSdata
  - andrewzm/INLA
